language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - pypy
  - pypy3
  - nightly
matrix:
  include:
    - python: "3.7"
      dist: xenial
    - python: "nightly"
      dist: xenial
  allow_failures:
  - python: pypy
install:
 - pip install -U pip
 - pip install -U wheel setuptools
 - pip install -U .[docs,test]
 - pip list
 - python --version
script:
 - python -m unittest discover
 - if [ -z "$SKIP_DOCS" ]; then python setup.py build_sphinx; fi
 - rst2html.py --strict README.rst README.html
